version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "4000:4000"
    depends_on:
      - database
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:4000
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis_data:
